services:
  - type: web
    name: voice-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: DEFAULT_MODEL
        value: deepseek/deepseek-chat-v3-0324:free
      - key: PYTHON_VERSION
        value: 3.8.0 